FROM centos:latest
MAINTAINER fabian.salamanca@rackspace.com
ENV DIR /opt/kube
WORKDIR $DIR
COPY kubectl /bin
RUN chmod 755 /bin/kubectl
RUN mkdir /home/jenkins
RUN chown -R 1001 /home/jenkins
USER 1001
