---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: quarkusapp
  namespace: aemxqa
spec:
  selector:
    matchLabels:
      app: quarkusapp
  replicas: 1
  template:
    metadata:
      labels:
        app: quarkusapp
    spec:
      containers:
      - name: quarkusapp
        image: fabstao/quarkusapp:latest
        ports:
        - containerPort: 8788
---
apiVersion: v1
kind: Service
metadata:
  name: quarkusapp-service
  namespace: aemxqa
spec:
  type: ClusterIP
  selector:
    app: quarkusapp
  ports:
    - port: 80
      targetPort: 8788
